import "./globals.css";
import Header from "./components/Header"
import FooterSection from "./components/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <Header />
        {children}
      
        <FooterSection />
        
      </body>
    </html>
  );
}
